import { chromium, devices } from 'playwright';
const shots = process.argv[2] || '/tmp/shots';
const browser = await chromium.launch();
const ctx = await browser.newContext({ ...devices['iPhone 13'], defaultBrowserType: undefined });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', m => m.type() === 'error' && errors.push(m.text()));
page.on('dialog', d => d.accept());
const okModal = async () => { await page.waitForSelector('#m-ok'); await page.click('#m-ok'); };
await page.goto('http://localhost:8765/');
await page.waitForSelector('#go-all');
await page.screenshot({ path: `${shots}/1-accueil.png` });
await page.click('#go-choose');
await page.click('[data-toggle="SV-G"]');
await page.check('input[data-code="SV-G-1"]');
await page.check('input[data-code="SV-G-3"]');
await page.screenshot({ path: `${shots}/2-choix.png`, fullPage: false });
await page.click('#start');
await page.waitForSelector('.flash');
await page.screenshot({ path: `${shots}/3-recto.png` });
await page.click('#reveal');
await page.screenshot({ path: `${shots}/4-verso.png` });
// 20 réponses : une sur trois ratée
for (let i = 0; i < 20; i++) {
  if (await page.$('#reveal')) await page.click('#reveal');
  const btn = await page.$(i % 3 === 0 ? '.grade .again' : '.grade .good');
  if (!btn) break;
  await btn.click();
}
await page.click('#undo');
const state = await page.evaluate(() => JSON.parse(localStorage.getItem('fc-bcpst-v1')));
console.log('cartes notées', Object.keys(state.cards).length, 'jour', JSON.stringify(Object.values(state.days)[0]), 'log', state.log.length);
await page.click('#btn-back');
await page.click('#btn-back');
await page.waitForSelector('#go-started');
await page.screenshot({ path: `${shots}/5-accueil-apres.png` });
console.log('accueil :', (await page.textContent('.hero')).replace(/\s+/g, ' ').trim());
console.log('commencés :', (await page.textContent('#go-started')).replace(/\s+/g, ' ').trim());
await page.click('#go-progress');
await page.screenshot({ path: `${shots}/6-progression.png`, fullPage: true });
await page.click('#btn-back');
await page.click('#btn-settings');
await page.setInputFiles('#xlsx', '/mnt/project-files/definitions/definitions_SVT.xlsx');
await okModal();
console.log('toast :', await page.textContent('#toast'));
await page.screenshot({ path: `${shots}/7-reglages.png`, fullPage: true });
const after = await page.evaluate(() => JSON.parse(localStorage.getItem('fc-bcpst-v1')));
console.log('progression conservée après import :', Object.keys(after.cards).length);
await page.click('#btn-back');
await page.click('#go-install');
await page.screenshot({ path: `${shots}/8-installer.png` });
const sw = await page.evaluate(async () => (await navigator.serviceWorker.getRegistration()) ? 'sw ok' : 'pas de sw');
console.log(sw, 'erreurs :', errors);
await browser.close();
